// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLjAlKXGMaMrjAYl7ws_3aX40tm1PjqN0',
    appId: '1:111228540017:web:a93e7587781e66013f77d0',
    messagingSenderId: '111228540017',
    projectId: 'fir-demo-f0384',
    authDomain: 'fir-demo-f0384.firebaseapp.com',
    storageBucket: 'fir-demo-f0384.firebasestorage.app',
    measurementId: 'G-G387KD3KKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uoSv1KUmSOi7Zokn_gtvh98ZEM8BrIg',
    appId: '1:111228540017:android:b886c89f0f5b03fd3f77d0',
    messagingSenderId: '111228540017',
    projectId: 'fir-demo-f0384',
    storageBucket: 'fir-demo-f0384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1DQf1Qr5CL-CgwflWmM54mydcyS6Qgs',
    appId: '1:111228540017:ios:e2db63aa2f7770fd3f77d0',
    messagingSenderId: '111228540017',
    projectId: 'fir-demo-f0384',
    storageBucket: 'fir-demo-f0384.firebasestorage.app',
    androidClientId: '111228540017-pjjil3vmh0adomchail6j3ghe8rugerq.apps.googleusercontent.com',
    iosClientId: '111228540017-goe0pi3nu1pea6d83ijlgtedo41bf9cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1DQf1Qr5CL-CgwflWmM54mydcyS6Qgs',
    appId: '1:111228540017:ios:e2db63aa2f7770fd3f77d0',
    messagingSenderId: '111228540017',
    projectId: 'fir-demo-f0384',
    storageBucket: 'fir-demo-f0384.firebasestorage.app',
    androidClientId: '111228540017-pjjil3vmh0adomchail6j3ghe8rugerq.apps.googleusercontent.com',
    iosClientId: '111228540017-goe0pi3nu1pea6d83ijlgtedo41bf9cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demofirebase',
  );

}